[app]
name = "demo1"
host = "0.0.0.0"
port = "8050"
key  = "this is your app key"

[mysql]
host = "150.158.11.116"
port = "3306"
username = "root"
password = "Hu.123456"
database = "go_course"

[log]
# // DebugLevel: "debug",
# // InfoLevel:  "info",
# // WarnLevel:  "warning",
# // ErrorLevel: "error",
# // FatalLevel: "fatal",
# // PanicLevel: "panic",
level = "debug"
format = "text"
to = "stdout"