[app]
name = "demo1"
host = "0.0.0.0"
port = "8050"
key  = "this is your app key"

[mysql]
host = ""
port = "3306"
username = "root"
password = "xxx"
database = "nextcloud"

[log]
# // DebugLevel: "debug",
# // InfoLevel:  "info",
# // WarnLevel:  "warning",
# // ErrorLevel: "error",
# // FatalLevel: "fatal",
# // PanicLevel: "panic",
level = "debug"
dir = "logs"
format = "text"
to = "stdout"